# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: session-db-storageclass
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-standard
#   replication-type: zonal-pd
# allowedTopologies:
#   - matchLabelExpressions:
#       - key: failure-domain.beta.kubernetes.io/zone
#         values:
#           - us-central1-f
# ---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: session-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi