apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: us-ag
  name: us-ag
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: us-ag
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kompose/
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/un-stream-nw: "true"
        io.kompose.service: us-ag
    spec:
      containers:
        - args:
            - sh
            - -c
            - /bin/wait-for-it.sh us-notification-mq:5672 --timeout=30 -- npm run runServer
          image: z4yross/us_ag
          name: us-ag
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-hub
status: {}
