apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: us-hlscache-db
  name: us-hlscache-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: us-hlscache-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kompose/
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/un-stream-nw: "true"
        io.kompose.service: us-hlscache-db
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./init.sh
          image: z4yross/us_hlscache_db
          name: us-hlscache-db
          ports:
            - containerPort: 6379
          resources: {}
          # securityContext:
          #   privileged: true
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-hub
status: {}
