apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: us-hls-ms
  name: us-hls-ms
spec:
  ports:
    - name: "8282"
      port: 8282
      targetPort: 8282
    - name: "8283"
      port: 8283
      targetPort: 8283
  selector:
    io.kompose.service: us-hls-ms
status:
  loadBalancer: {}
