apiVersion: v1
kind: ConfigMap
metadata:
  name: us-session-db-config
  labels:
    app: postgresql-db
data:
  # POSTGRES_DB: testdb
  # POSTGRES_USER: testdbuser
  # POSTGRES_PASSWORD: testdbuserpassword
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: postgres