apiVersion: v1
kind: Service
metadata:
  name: pilb-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    io.kompose.service: private-internallb
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: us-web-fe
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP