apiVersion: v1
kind: Service
metadata:
  name: pilb-hls-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    io.kompose.service: private-hls-internallb
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: us-hls-ms
  ports:
  - port: 80
    targetPort: 8283
    protocol: TCP