apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: un-stream-nw
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/un-stream-nw: "true"
  podSelector:
    matchLabels:
      io.kompose.network/un-stream-nw: "true"
